version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      - db
    environment:
      RUST_ENV: main
      DATABASE_URL: postgresql://neondb_owner:npg_8bkSqnm7fDVY@ep-young-tooth-a1hqtxg7-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      JWT_SECRET: adprojomox123
      HOST: 0.0.0.0
      PORT: 80
    ports:
      - "8080:80"
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pookiebear1902
      POSTGRES_DB: auth_microservice
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
