name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/auth:latest

      - name: Trigger Koyeb redeploy
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.KOYEB_API_TOKEN }}" \
            https://app.koyeb.com/v1/apps/386f4a7d-63b4-4221-b391-c265816136aa/services/fbcf6c60-6e41-49ce-b962-003309c08940/deploy
